(terraform): improve cleanup step to remove RG and state

diff --git a/terraform/scripts/init-variables b/terraform/scripts/init-variables
--- a/terraform/scripts/init-variables
+++ b/terraform/scripts/init-variables
@@ -2,8 +2,6 @@
 
 CDIR=$(dirname "${BASH_SOURCE}")
 
-set -x
-
 echo $AZURE_LOCATION
 echo $AZURE_VM_KEY_NAME
 echo $AZURE_VHD_URI
@@ -20,21 +18,51 @@ echo $HYPERKUBE_IMAGE
 echo $HYPERKUBE_TAG
 echo $PKI_IP
 
-set +x
-
-CRED_ARRAY=($(az ad sp create-for-rbac -n cluster-${CLUSTER_NAME} -o tsv | cut -f1,4,5 -d'	'))
-SUBSCRIPTION_ID=`az account show  -o tsv| cut -f2 -d'	'`
+SP_PATH=${SP_PATH:-~/.azure/acstack-sp.json}
+SUBSCRIPTION_ID=${SUBSCRIPTION_ID:-`az account show --query="id" | tr -d '"'`}
 TOKEN_ID=$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 6 | head -n 1)
 TOKEN_CONTENT=$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 16 | head -n 1)
 BOOTSTRAP_TOKEN="${TOKEN_ID}.${TOKEN_CONTENT}"
+
+echo "Subscription ID: ${SUBSCRIPTION_ID}"
+echo "Location: ${AZURE_LOCATION}"
+echo "Cluster Name: ${CLUSTER_NAME}"
+echo "Service Principal Path: ${SP_PATH}"
+
+if [ -a "${SP_PATH}" ]; then
+	client_id=`cat ${SP_PATH} | jq -r .appId`
+	client_secret=`cat ${SP_PATH} | jq -r .password`
+	tenant_id=`cat ${SP_PATH} | jq -r .tenant`
+else
+	echo "Service principal file not found! Generating one @ ${SP_PATH}"
+	az ad sp create-for-rbac -n azure-stack-sp-${TOKEN_ID} -o json > ${SP_PATH}
+	client_id=`cat ${SP_PATH} | jq -r .appId`
+	client_secret=`cat ${SP_PATH} | jq -r .password`
+	tenant_id=`cat ${SP_PATH} | jq -r .tenant`
+fi
+
+if [ -z "${client_id}" ]; then
+	echo "client_id was not set! Something happened when generating the service principal or when trying to read the sp file!"
+	exit 1
+fi
+
+if [ -z "${client_secret}" ]; then
+	echo "client_secret was not set! Something happened when generating the service principal or when trying to read the sp file!"
+	exit 1
+fi
+
+if [ -z "${tenant_id}" ]; then
+	echo "tenant_id was not set! Something happened when generating the service principal or when trying to read the sp file!"
+	exit 1
+fi
 
 cat <<EOF > terraform.tfvars
 # Generated by scripts/init-variables.sh
 azure = {
   subscription_id = "${SUBSCRIPTION_ID}"
-  client_id       = "${CRED_ARRAY[0]}"
-  client_secret   = "${CRED_ARRAY[1]}"
-  tenant_id       = "${CRED_ARRAY[2]}"
+  client_id       = "${client_id}"
+  client_secret   = "${client_secret}"
+  tenant_id       = "${tenant_id}"
 }
 
 cidr = {
